# typed: false
# frozen_string_literal: true

# Homebrew formula for shoka — your repository bookshelf.
# Auto-generated by yukimemi/shoka .github/workflows/homebrew.yml.
# Do not edit by hand; changes are overwritten on the next release.
class Shoka < Formula
  desc "Repository workspace manager: jj-aware successor to ghq / rhq with a TUI dashboard"
  homepage "https://github.com/yukimemi/shoka"
  version "0.26.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yukimemi/shoka/releases/download/v0.26.0/shoka-aarch64-apple-darwin.tar.gz"
      sha256 "4284b7cc0ee34a8b4d4e996bf64362379595d1e83672f97ec3d1a6e169539bc6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yukimemi/shoka/releases/download/v0.26.0/shoka-x86_64-unknown-linux-musl.tar.gz"
      sha256 "96e4a34b4cf5926efc4c93195552992c8b03e74f9a0bd3b4257612ae6cfcd7f6"
    end
  end

  def install
    bin.install "shoka"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shoka --version")
  end
end
