# typed: false
# frozen_string_literal: true

# Homebrew formula for shoka — your repository bookshelf.
# Auto-generated by yukimemi/shoka .github/workflows/homebrew.yml.
# Do not edit by hand; changes are overwritten on the next release.
class Shoka < Formula
  desc "Repository workspace manager: jj-aware successor to ghq / rhq with a TUI dashboard"
  homepage "https://github.com/yukimemi/shoka"
  version "0.24.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yukimemi/shoka/releases/download/v0.24.0/shoka-aarch64-apple-darwin.tar.gz"
      sha256 "c51d61c680297acd81f38a51c36c31f4f5ae11276678641b3ce8fb6fee28b89e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yukimemi/shoka/releases/download/v0.24.0/shoka-x86_64-unknown-linux-musl.tar.gz"
      sha256 "7a0bfbe8906039a01d720bc2919de6fa304685646b681b5ff3d3654821578da6"
    end
  end

  def install
    bin.install "shoka"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shoka --version")
  end
end
